BulkyBookWeb/Areas/Admin/Controllers/CategoryController.cs
using BulkBook.DataAccess;
using BulkBook.DataAccess.Repository.IRepository;
using BulkBook.Models;
using BulkBook.UtilityLayer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulkBookWeb.Controllers
{
    [Area("Admin")]
    [Authorize(Roles=SD.Role_Admin)]     



  public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> objCategoryList=_unitOfWork.Category.GetAll();
            return View(objCategoryList);
        } 
        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if (obj.Name==obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("CustomError","Errrrorrr");
            }

            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Category created successfuly";
                return RedirectToAction("Index");
            }

            return View(obj); 

        }


        //GET
        public IActionResult? Edit(int? id)
        {
            if (id==null || id==0)
            {
                return NotFound();
            }

           // var categoryFromDb = _db.Categories.Find(id);
            var categoryFromDbFirst = _unitOfWork.Category.GetFirstOrDefault(u=>u.Id==id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u => u.Id == id);
            if (categoryFromDbFirst==null)
            {
                return NotFound();
            }
            return View(categoryFromDbFirst);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("CustomError", "Errrrorrr");
            }

            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Category updated successfuly";
                return RedirectToAction("Index");
            }

            return View(obj);

        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var categoryFromDbFirst = _unitOfWork.Category.GetFirstOrDefault(u=>u.Id==id);
            //var categoryFromDbFirst = _db.Categories.FirstOrDefault(u=>u.Id==id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u => u.Id == id);
            if (categoryFromDbFirst == null)
            {
                return NotFound();
            }
            return View(categoryFromDbFirst);
        }


        //POST
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
          var obj= _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);
            if (obj==null)
          {
              return NotFound();
          }
          _unitOfWork.Category.Remove(obj);
          _unitOfWork.Save();
          TempData["success"] = "Category deleted successfuly";
            return RedirectToAction("Index");

        }


    }
}

BulkyBookWeb/Areas/Admin/Controllers/CompanyController.cs
using BulkBook.DataAccess.Repository.IRepository;
using BulkBook.Models;
using BulkBook.Models.ViewModels;
using BulkBook.UtilityLayer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BulkBookWeb.Controllers
{

    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvirmoment;

        public CompanyController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvirmoment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvirmoment = hostEnvirmoment;
        }

        public IActionResult Index()
        {
            return View();
        }

        //Get
        public IActionResult Upsert(int? id) //Id ile kategori ayrıntıları alınır görüntülenir ,? işareti ile nullable olduğunu belirttik.
        {
            //Product View Modeli içinden önce getall ile çağırıp içinden istedğimiz kısımları selectlist item ile seçtik
            Company company = new();
            if (id == null || id == 0)
            {
                //create product
                //ViewBag.CategoryList=CategoryList;
                //ViewData["CoverTypeList"] = CoverTypeList;
                return View(company);
            }
            else
            { 
                company= _unitOfWork.Company.GetFirstOrDefault(u => u.Id == id);
                return View(company);
                //update product
            }

        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Company obj)
        {
            if (ModelState.IsValid)
            {
                 
                if (obj.Id==0)
                {
                    _unitOfWork.Company.Add(obj);
                    TempData["success"] = "Company Created successfuly";

                }
                else
                {
                    _unitOfWork.Company.Update(obj);
                    TempData["success"] = "Company Created successfuly";
                }
              
                _unitOfWork.Save();
               
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult GetAll()
        {
            var companyList = _unitOfWork.Company.GetAll();
            return Json(new { data = companyList });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var obj = _unitOfWork.Company.GetFirstOrDefault(u => u.Id == id);
            if (obj==null)
            {
                return Json(new {success=false,message="Error while deleting"});
            }
          
            _unitOfWork.Company.Remove(obj);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Deleted successfuly" });
        }


       
    }

}

BulkyBookWeb/Areas/Admin/Controllers/ProductController.cs
using BulkBook.DataAccess.Repository.IRepository;
using BulkBook.Models.ViewModels;
using BulkBook.UtilityLayer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BulkBookWeb.Controllers
{

    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvirmoment;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvirmoment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvirmoment = hostEnvirmoment;
        }

        public IActionResult Index()
        {
            return View();
        }

        //Get
        public IActionResult Upsert(int? id) //Id ile kategori ayrıntıları alınır görüntülenir ,? işareti ile nullable olduğunu belirttik.
        {
            //Product View Modeli içinden önce getall ile çağırıp içinden istedğimiz kısımları selectlist item ile seçtik
            ProductVM productVM = new()
            {
                Product = new(),
                CategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                CoverTypeList = _unitOfWork.CoverType.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
            };
            if (id == null || id == 0)
            {
                //create product
                //ViewBag.CategoryList=CategoryList;
                //ViewData["CoverTypeList"] = CoverTypeList;
                return View(productVM);
            }
            else
            { 
                productVM.Product = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
                return View(productVM);
                //update product
            }

        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM obj, IFormFile file) //IFormFile ile image vb. meedyaları yükleyebilme imkanı elde ettik.
        {
            if (ModelState.IsValid)
            {
                 string wwwrootPath = _hostEnvirmoment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwrootPath, @"images\products");
                    var extension = Path.GetExtension(file.FileName);

                    if (obj.Product.ImageUrl!=null)
                    {
                        var oldImagePath=Path.Combine(wwwrootPath,obj.Product.ImageUrl.TrimStart('\\') );
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    
                    }

                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    //Burada Product View Modeli altındaki Product classına ardından onun içindeki ImageURL kısmına atamamızı yaptık.
                    obj.Product.ImageUrl = @"\images\products\" + fileName + extension;

                }

               
                if (obj.Product.Id == 0)
                {
                    _unitOfWork.Product.Add(obj.Product); //Veri tabanına kayıt
                }
                else
                {
                    _unitOfWork.Product.Update(obj.Product);
                }
              
                _unitOfWork.Save();
                TempData["success"] = "Product Created successfuly";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var obj = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
            if (obj==null)
            {
                return Json(new {success=false,message="Error while deleting"});
            }
            var oldImagesPath=Path.Combine(_hostEnvirmoment.WebRootPath,obj.ImageUrl.Trim('\\'));
            if (System.IO.File.Exists(oldImagesPath))
            {
                System.IO.File.Delete(oldImagesPath);
            }
            _unitOfWork.Product.Remove(obj);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Deleted successfuly" });
        }


        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var productList = _unitOfWork.Product.GetAll(includeProperties:"Category,CoverType");
            return Json(new { data = productList });
        }

        #endregion
    }

}

BulkyBookWeb/ViewComponents/ShoppingCartViewComponent.cs
using BulkBook.DataAccess.Repository.IRepository;
using BulkBook.UtilityLayer;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BulkyBookWeb.ViewComponents
{
    public class ShoppingCartViewComponent:ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
           _unitOfWork = unitOfWork;
        }


        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim !=null)
            {
                if (HttpContext.Session.GetInt32(SD.SessionCart)!=null)
                {
                    return View(HttpContext.Session.GetInt32(SD.SessionCart));
                }
                else
                {
                    HttpContext.Session.SetInt32(SD.SessionCart,
                        _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value).ToList().Count);
                    return View(HttpContext.Session.GetInt32(SD.SessionCart));
                }
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
                
            }
        }
    }
}

BulkyBookWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using BulkBook.UtilityLayer
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkBookWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/css/bootswatchTheme.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"/>
    @*<link rel="stylesheet" href="/css/profile.css" />*@
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
    <script src="https://cdn.tiny.cloud/1/oqc7f4x5dhc4pdjpw3kzzt8jt5llabar6g2hwnn1d881vgxs/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:rebeccapurple">
        <div class="container-fluid">
                <a class="nav-link " style="color:aliceblue" asp-area="Customer" asp-controller="Home" asp-action="Index">Hammal</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link " asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                    </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Admin" asp-controller="CoverType" asp-action="Index">CoverType</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                        </li>
                        
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                    @await Component.InvokeAsync("ShoppingCart")
                                </a>
                            </li>
                        
                         
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">
                                Manage Order
                            </a>
                        </li>
                    </ul>
                <partial name ="_LoginPartial"/>

              @*  <form class="d-flex">
                    <input class="form-control me-sm-2" type="text" placeholder="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                </form>*@
            </div>
        </div>
    </nav>


</header>
<div class="container-fluid">
    <main role="main" class="pb-3">
        <partial name="_Notification"/>
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - BulkBookWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>



@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BulkyBookWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["error"]');
    </script>
}